[feature] Implement an Enumerables module
Mindo-Joseph/enumerables_ruby pull request #1
Opened 2020-04-14 14:04 UTC by Mindo-Joseph

### What does this PR do?
This PR creates an enumerable module and implements the following methods:
1. my_each
2. my_each_with_index
3. my_select
4. my_all?
5. my_none?
6. my_count
7. my_any?
8. my_map
9. my_inject

#### How should this be manually tested?
- Click on the repl.it button in the README.md file and run the given code examples at the bottom of the enumerables.rb file

2020-04-14 19:31 UTC, suretrust requested changes
Hi @Mindo-Joseph, 👋 

### Great job thus far! 🙌 Please see my comments on your code. 👇 

- [x] There are about 20 failing cases, let's fix these.

**Kindly submit for another code review request once these have been fixed.** _Happy coding!_ 🎉

2020-04-14 19:31 UTC, suretrust commented on enumerables.rb
> +  end
* [x] should have working `my_each` identical and returns the same thing as ruby's [`each`](https://ruby-doc.org/core-2.6.4/Array.html#method-i-each). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5].my_each.class != [1,2,3,4,5].each.class
```

2020-04-14 19:31 UTC, suretrust commented on enumerables.rb
> +  end
* [x] should have working `my_each_with_index` identical and returns the same thing as ruby's [`each_with_index`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-each_with_index). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_each_with_index.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5].my_each_with_index.class != [1,2,3,4,5].each_with_index.class
```

2020-04-14 19:31 UTC, suretrust commented on enumerables.rb
> +  end
* [x] should have working `my_select` identical and returns the same thing as ruby's [`select`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-select). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_select.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5].my_select.class != [1,2,3,4,5].select.class
```

2020-04-14 19:31 UTC, suretrust commented on enumerables.rb
> +  end
* [ ] should have working `my_all?` identical and returns the same thing as ruby's [`all?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-all-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_all.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby 
[1, true, 'hi', []].my_all? != [1, true, 'hi', []].all?

[1,2,3,4,5].my_all?(Integer) != [1,2,3,4,5].all?(Integer)

['saheed', 'oladele', 'suretrust'].my_all?(/d/) != ['saheed', 'oladele', 'suretrust'].all?(/d/)

[1,2,3,4,5].my_all?(3) != [1,2,3,4,5].all?(3)
```

2020-04-14 19:31 UTC, suretrust commented on enumerables.rb
> +  end
* [ ] should have working `my_any?` identical and returns the same thing as ruby's [`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1, true, 'hi', []].my_any? != [1, true, 'hi', []].any?

[1,2,3,4,5].my_any?(Integer) != [1,2,3,4,5].any?(Integer)

['saheed', 'oladele', 'suretrust'].my_any?(/z/) != ['saheed', 'oladele', 'suretrust'].any?(/z/)

['saheed', 'oladele', 'suretrust'].my_any?('saheed') != ['saheed', 'oladele', 'suretrust'].any?('saheed')
```

2020-04-14 19:31 UTC, suretrust commented on enumerables.rb
> +  end
* [ ] should have working `my_none?` identical and returns the same thing as ruby's [`none?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-none-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_none.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1, false, 'hi', []].my_none? != [1, false, 'hi', []].none?

[1,2,3,4,5].my_none?(String) != [1,2,3,4,5].none?(String)

['sure', 'trust'].my_none?(/z/) != ['sure', 'trust'].none?(/z/)

['sure', 'trust'].my_none?(5) != ['sure', 'trust'].none?(5)
```

2020-04-14 19:31 UTC, suretrust commented on enumerables.rb
> +  end
* [ ] should have working `my_count` identical and returns the same thing as ruby's [`count`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-count). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_count.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5].my_count != [1,2,3,4,5].count

[1,2,3,4,5].my_count { |num| num < (1 + 5) / 2 } != [1,2,3,4,5].count { |num| num < (1 + 5) / 2 }
```

2020-04-14 19:31 UTC, suretrust commented on enumerables.rb
> +  end
* [ ] should have working `my_map` identical and returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
[1,2,3,4,5].my_map.class != [1,2,3,4,5].map.class
```

2020-04-14 19:31 UTC, suretrust commented on enumerables.rb
> +end
* [ ] should have working `my_inject` identical and returns the same thing as ruby's [`inject`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-inject). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_inject.png) from [Odin](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks#assignment-2))
```ruby
(5..50).my_inject(4) { |prod, n| prod * n } != (5..50).inject(4) { |prod, n| prod * n }

[1,2,3,4,5].my_inject(:+) != [1,2,3,4,5].inject(:+)
```

2020-04-15 18:51 UTC, majovanilla requested changes
## You did a *good* job on this project! 💜 

Some tests are still not passing. 

## Please, make all REQUIRED changes below and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-04-15 18:51 UTC, majovanilla commented on enumerables.rb
> +    end
Your method is not working correctly when given a block. It should return all the elements in you enumerable and now it's not doing that.

2020-04-15 18:51 UTC, majovanilla commented on enumerables.rb
> +  end
Please check your method when a block is given. It's not working right now.

2020-04-15 18:51 UTC, majovanilla commented on enumerables.rb
> +  end
Please check your method when a block is given. It's not working right now. Should return true if it never returns false or nil.

Should return true when no block or argument is given and all elements are truthy.
Should return an answer if you give a class as an argument.
Should return an answer if you give a regex as an argument.
Should return an answer if you give a number as an argument.

2020-04-15 18:51 UTC, majovanilla commented on enumerables.rb
> +  end
Please check your method when a block is given. It's not working right now. Should return true if it never returns false or nil.
Should return an answer if you give a class as an argument.
Should return an answer if you give a regex as an argument.

2020-04-15 18:51 UTC, majovanilla commented on enumerables.rb
> +  end
Please check your method when a block is given. It's not working right now. Should return true if it never returns false or nil.
Should return an answer if you give a class as an argument.
Should return an answer if you give a regex as an argument.

2020-04-15 18:51 UTC, majovanilla commented on enumerables.rb
> +  end
Please check your method when a block is given. It's not working right now.

2020-04-15 18:51 UTC, majovanilla commented on enumerables.rb
> +  end
Should return an array with the result when you pass a block.

2020-04-15 18:51 UTC, majovanilla commented on enumerables.rb
> +  end
Should combine all elements when passing a block to apply an operation to them.
Should combine all elements when passing a symbol to apply an operation to them.

2020-04-17 05:31 UTC, maelfosso approved these changes
# Congratulations :clap: 

It's OK now :+1:  You can merge it now :smile: 
Good look with the next step :handshake: 

Mael FOSSO

2020-04-17 13:21 UTC, merged