Feature/test enumerables
Mindo-Joseph/enumerables_ruby pull request #3
Opened 2020-05-11 15:47 UTC by Mindo-Joseph

#### What does this PR do?
Implements tests for enumerable methods in Ruby
#### Description of Task to be completed?
Write tests for the previously completed project on Ruby Enumerables
#### How should this be manually tested?
Clone the repository into your machine and inside the terminal run 'rspec'

2020-05-11 20:37 UTC, kobiyoyo requested changes
## Hi Team    ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [ ]  Check comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-05-11 20:37 UTC, kobiyoyo commented on spec/enumerables_spec.rb
> +  end
Let's write test for when a block is given

2020-05-11 20:37 UTC, kobiyoyo commented on spec/enumerables_spec.rb
> +  end
Let's write test for when Regex is passed as an argument

2020-05-11 20:37 UTC, kobiyoyo commented on spec/enumerables_spec.rb
> +  end
Let's write test for when Regex is passed as an argument

2020-05-11 20:37 UTC, kobiyoyo commented on spec/enumerables_spec.rb
> +  end
Let's write test for when Regex is passed as an argument

2020-05-11 20:37 UTC, kobiyoyo commented on spec/enumerables_spec.rb
> +  end
Let's write test for when a block is given

2020-05-11 20:37 UTC, kobiyoyo commented on spec/enumerables_spec.rb
> +  end
Let's write test for when a block is given

2020-05-11 20:37 UTC, kobiyoyo commented on spec/enumerables_spec.rb
> +    end
Let's write test for when a block is given

2020-05-12 06:49 UTC, maelfosso approved these changes
# Congratulations :clap: 

Thank you for the changes done!
You can merge it now :+1: 
Good continuation :handshake: 

Mael FOSSO

2020-05-12 06:55 UTC, merged